steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/local-gantry-402314/my-docker-repo/cancerout-game:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/local-gantry-402314/my-docker-repo/cancerout-game:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'cancerout-game'
  - '--image=us-central1-docker.pkg.dev/local-gantry-402314/my-docker-repo/cancerout-game:$SHORT_SHA'
  - '--region=us-central1'
  - '--platform=managed'
  - '--allow-unauthenticated'
